### ISSUE TITLE
[Suggestion/Discussion] Consider local ".eslintignore" file to evaluate open files

### ISSUE THREAD

**Issue by andre-f-paggi** [jwldnr/VisualLinter#16]
I noticed that the extension only checks opened files.

Is it possible to add support for checking only files not ignored by ".eslintignore" file?

Is this suggestion valid for the intention of the extension and the creator?

Thanks!

**Comment by jwldnr** [comment]
This is definitely something that should be a part of this extension-- thank you for your suggestion!

This should also be easily implemented since I already have the traversing of directories to find config relative to the file being linted logic in place. (they should be similar)

Question:
The traversing of directories to find the `.eslintignore` file doesn't have to be as deep as finding the config, no?
Up to and including solution root should be enough? (much like the old find config behavior)

**Comment by jwldnr** [comment]
addressed and implemented in #17 
please open a new issue on GitHub if you you experience any problems.

**Comment by jwldnr** [comment]
A new version `1.0.185` will soon be available on the Marketplace.
