### ISSUE TITLE
Linting not running for .jsx files

### ISSUE THREAD

**Issue by jsaarija** [jwldnr/VisualLinter#18]
### Installed product versions
- Visual Studio Enterprise 2017 
- This extension: 1.0.187

### Description
It looks like VisualLinter only runs ESLint against .js files. Unfortunately, most of the javascript files in our project are .jsx files, being a React project. I'm not an ESLint expert by any means but my understanding is that ESLint needs to be specifically run with arguments that include .jsx files in addition to .js files, while also configuring the .eslintrc file properly. The local configuration file in our project should be fine - ESLint works in Visual Studio Code with the same config file. Likewise VisualLinter works for the .js files in the project just fine.

Alternatively is this already possible and I'm just missing something?

For reference our .eslintrc file is configured like this (rules omitted for brevity):

```javascript
{
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended"
  ],
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": false
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "ecmaFeatures": {
      "arrowFunctions": true,
      "jsx": true,
      "experimentalObjectRestSpread": true,
      "spread": true
    },
    "sourceType": "module"
  },
  "plugins": [
    "react"
  ],
  "rules": {
    // snipped for brevity
  },
  "globals": {}
}
```

### Steps to recreate
1. Add .jsx files into Visual Studio project
2. Configure .eslintrc to support React/jsx
3. Run linter

### Current behavior
Linter does not run against .jsx files. No ESLint findings for .jsx files come up on Error List.

### Expected behavior
ESLint findings for .jsx files should be shown just like for .js files.

**Comment by jwldnr** [comment]
I'll have a look at this!

**Comment by jwldnr** [comment]
Fixed in #19 

A new version `1.0.189` will soon be available on the Marketplace.
I'll go ahead and close this issue. Please open a new issue if you experience any problems.

**Comment by jsaarija** [comment]
Yes, this works now. Thank you!

**Comment by paparent** [comment]
Hi,

Dunno if I should write here or open a new ticket. I'm working on vuejs and need the .vue extension too :) That would be awesome!

Thanks..

**Comment by jwldnr** [comment]
Hi @paparent the prefered way would be to create a new issue so that I can reference it in the pull request 👍 its no problem though, I'll add it to the list.

**Comment by jwldnr** [comment]
@paparent Ok, so I looked into this a bit more and when you say `.vue` extension you mean [vue single file components](https://vuejs.org/v2/guide/single-file-components.html) correct? Because in that case I'd have to target only the `<script>..</script>` block and lint its content.

Please make a new issue and I'll look into implementing this in an upcoming release.

**Comment by paparent** [comment]
@jwldnr Thanks :) it's #23 !

**Comment by rbrugnollo** [comment]
Hi, I'm running version 1.0.238 and the .jsx files are still not getting anylized.

I tried using 2 .eslintrc versions:

`{
  "extends": "airbnb",
  "plugins": [
    "react"
  ]
}`

and this:

`{
  "extends": "airbnb"
}`

Do I need to add more info to my config file to get it to work?

Thanks!

**Comment by jwldnr** [comment]
@rbrugnollo No it should work. However since the `1.0.238` update you have to enable `.jsx` language support in Visual Studio under `Tools -> Options.. -> VisualLinter` (it is disabled by default since it needs additional plugins) see the [language support](https://github.com/jwldnr/VisualLinter#language-support) section of the readme.

If it still does not work after enabling `.jsx` language support in options-- open a new issue and I'll have a look!

**Comment by rbrugnollo** [comment]
That was it, thank you very much @jwldnr .
