### ISSUE TITLE
Setting for using global eslint seems broken

### ISSUE THREAD

**Issue by fspafford** [jwldnr/VisualLinter#30]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.0.238

### Description
I installed eslint globally, and marked the global option in the Visual Studio configuration, but the output panel from VisualLinter says "fatal: no local eslint config found". I rebooted my PC but get the same result. Would I have better results if I removed eslint and reinstalled non-globally?

### Steps to recreate
1. use npm to install eslint globally
2. in Visual Studio, for VisualLinter, mark the global option
3. open a JavaScript file
4. note the output panel from VisualLinter says "fatal: no local eslint config found"

### Current behavior
It does not seem to honor the global setting.

### Expected behavior
Honor the global setting, so that when set the global installation of eslint is used.

**Comment by jwldnr** [comment]
Thank you for the feedback @fspafford

If you want to get started with the extension fast then switching to the local variant should help since all options are set to default false.

However with that said I would like to get to the bottom of this problem:

Have you tried unchecking/checking the option again after you first received the "local" error message?

I am planning on adding a verbose logging option that will log to the output window when an options value is changed. This will help determine if the option is actually set or not. 

I'll update this issue once a version with verbose logging is available for you to test.

**Comment by fspafford** [comment]
You are welcome!

I have tried unchecking/checking the option, and see the same behavior.

**Comment by jwldnr** [comment]
@fspafford I've pushed a new version (`1.0.240`) of VisualLinter to the Marketplace which should be available for download in a minute. 

This new update adds a new option `Enable verbose logging` under
`Tools -> Options... -> VisualLinter -> Advanced`, please see below:

![verboselogging](https://user-images.githubusercontent.com/11960421/33060355-4228dfba-ce98-11e7-8a40-83e8e12652a3.png)

Once this option is checked, click `OK` to save the options and re-open the options window using
`Tools -> Options...` and all the option values of the view you're standing on (either `General` or `Advanced` should be logged in the output window.
Remember to clear the output window between opening the options window.

If you check the `Use global ESLint installation instead of local` and click `OK`, is the value for property `UseGlobalEslint` set to true?

**Comment by fspafford** [comment]
Yes. 

The output is:
[GetPropertyValue] ShouldOverrideEslint value is False
[GetPropertyValue] EslintOverridePath value is 
[GetPropertyValue] ShouldOverrideEslintConfig value is False
[GetPropertyValue] EslintConfigOverridePath value is 
[GetPropertyValue] ShouldOverrideEslintIgnore value is False
[GetPropertyValue] EslintIgnoreOverridePath value is 
[GetPropertyValue] EnableVerboseLogging value is True
[GetPropertyValue] UseGlobalEslint value is True
[GetPropertyValue] EnableHtmlLanguageSupport value is False
[GetPropertyValue] EnableJavaScriptLanguageSupport value is True
[GetPropertyValue] EnableReactLanguageSupport value is False
[GetPropertyValue] EnableVueLanguageSupport value is False
[GetPropertyValue] UsePersonalConfig value is False
[GetPropertyValue] DisableEslintIgnore value is False

**Comment by jwldnr** [comment]
Ok that's strange. But good. Now we'll have to see what value is used when actually linting. I'll have to push an update for you to test. I'll update here once it's available.

**Comment by jwldnr** [comment]
Still unable to reproduce on my end,  but I've pushed a new version (`1.0.241`) to the Marketplace which should be available in just a minute. I've changed the name of the option so you'll need to re-enable it under Advanced options.

Ensure that option `UseGlobalEslint` is `true` when you open options (as you did previously), then save a javascript file you wanted to lint in Visual Studio and report back with the output here!

**Comment by jwldnr** [comment]
Hi @fspafford
Yep! that's exactly it, and should definitely be clarified, because:

You've told the extension to use a global ESLint **installation** (eg `npm install eslint --global`) but using a local ESLint **config**, is still default unless `Use personal ESLint config instead of local` is checked (value `true`) in options.

I'll update the notes section of the readme to include this information for future reference.
Thank you for your contribution Frank!
