### ISSUE TITLE
Add option to autofix issues on save

### ISSUE THREAD

**Issue by bpugh** [jwldnr/VisualLinter#37]
### Installed product versions
- Visual Studio 2017 professional
- VisualLinter 1.1.47

### Description
The eslint extension for VS Code has an option to run eslint with the `--fix` parameter on save which will automatically fix any fixable issues in the current file. If this is feasible to implement it would be really nice to have this option in VisualLinter. Thoughts?

Thanks for the great extension!

**Comment by jwldnr** [comment]
Hi @bpugh and thanks for the feedback!

This is something I've been meaning to implement sometime _soon_. It is even listed in the [CHANGELOG.md](https://github.com/jwldnr/VisualLinter/blob/master/CHANGELOG.md).
However It is not as easy to implement as one would think, having to replace the text in the buffer and not mess up Visual Studio features can prove quite difficult.

But since this now has been requested I'll have to take a look, wont I? 😄 
I'll keep this issue open and update here when I've reached a conclusion!

**Comment by poganytamastsys** [comment]
Any news on implementing this feature?

**Comment by cymptom** [comment]
As @giolvani said, the `Format Document On Save` extension allows specifying a command to be run on save. So, if it makes it simpler to implement, `VisualLinter` might only need to expose a Visual Studio Command for running ESLint on the active file. 

There is a workaround for doing this now, but it's not pretty. It involves configuring an "External Tool" command -- something like this: 
`cmd.exe /c node $(ProjectDir)/node_modules/eslint/bin/eslint.js $(ItemPath) --fix`

Then you can have `Format Document On Save` target that Command. 

It would be much nicer if `VisualLinter` registered a command to that effect in VS.

**Comment by woldner** [comment]
Sorry everyone; but the development of this extension has been suspended. 
You can read more about it here:
https://github.com/jwldnr/VisualLinter#deprecated
