### ISSUE TITLE
Feature request: integrate also csslint

### ISSUE THREAD

**Issue by glat** [jwldnr/VisualLinter#38]
Any plans to integrate also support for csslint to replace integrated VS 2017 support?

**Comment by jwldnr** [comment]
Hi @glat and thank you for your feedback!

I have thought about this and I would like to implement this if enough people would request this feature.

If you're just now reading this and would like this feature to be implemented, let me know.
I'm sorry to say, but until then this feature is lower priority because I've just started working on another project, and don't have much spare time left.

Pull requests are always welcome 👍

**Comment by glat** [comment]
I sent a PR just not to add support for Stylelint.
Check it and let me know.
Kind regards

**Comment by jwldnr** [comment]
Cool @glat I'll check it out.
