### ISSUE TITLE
Visual Linter not displaying any error in Visual Studio

### ISSUE THREAD

**Issue by Indigo744** [jwldnr/VisualLinter#63]
### Installed product versions
- Visual Studio: 2019 Professional (16.3.7)
- This extension: 1.1.0

### Description
No error are shown in Visual Studio.

I have Visual Linter configured for *.ts and *.tsx files only.
ESlint is setup locally and working.

### Steps to recreate
1. Run ESLint in command line
1. See that errors are found
1. In Visual Studio, open a TSX file
1. See no errors

### Current behavior
No error are shown.

If I look at the spawned process using ProcessExplorer, I can see that ESLint is launched with all correct parameters:
```
C:\Windows\system32\cmd.exe /c ""(redacted)\node_modules\.bin\eslint.cmd" "(redacted)\Component.tsx" --format="json" --config="(redacted)\.eslintrc.js""
```

If I launch the command myself, I get a correct result with the error:
```json
[{
        "filePath": "(redacted)\\Component.tsx",
        "messages": [{
                "ruleId": "eqeqeq",
                "severity": 2,
                "message": "Expected '===' and instead saw '=='.",
                "line": 53,
                "column": 43,
                "nodeType": "BinaryExpression",
                "messageId": "unexpected",
                "endLine": 53,
                "endColumn": 45
            }
        ],
        "errorCount": 1,
        "warningCount": 0,
        "fixableErrorCount": 0,
        "fixableWarningCount": 0,
        "source": "(redacted)"
    }
]
```

I activated the debug mode, and I only see this:
```
ShouldOverrideEslint: False
UseGlobalEslint: False
using local eslint @ (redacted)\node_modules\.bin\eslint.cmd
ShouldOverrideEslintConfig: False
UsePersonalConfig: False
DisableIgnorePath: False
ShouldOverrideEslintIgnore: False
using eslint ignore @ not found
```
Not really helpful.

### Expected behavior

Red squiggles should be shown in Visual Studio where ESLint found errors.

Also, DEBUG mode should output more information to help understand what is really going on behind the scene. Like "launching tool path..." and "got x results" and "showing x results" and so on...

**Comment by Indigo744** [comment]
Ah, more information!

Interestingly, I was able to make it work by activating JS file:
![image](https://user-images.githubusercontent.com/7137528/68014600-5864c500-fc90-11e9-862b-f0b09a437358.png) ==> ![image](https://user-images.githubusercontent.com/7137528/68014611-5ef33c80-fc90-11e9-97a4-75c4619047c8.png)

If I can make a wild guess, the related error (`eqeqeq`) is a Javascript error (and not a TypeScript error) and maybe somewhere you are actively filtering JS error in TS file if the JS extension is not activated?

If I have some time I'll take a look in the source.

**Comment by Indigo744** [comment]
Wow now I can't reproduce what I just said. The error is simply gone again, with or without activating JS files.

There is something seriously wrong with this plugin.

**Comment by Mrsevic** [comment]
I have experienced the same behaviour, I just wanted to enable the linting for *.ts files but to no avail.

**Comment by Indigo744** [comment]
Since I opened this issue, this plugin has been working on and off. Sometimes it shows an error, sometimes it doesn't. Sometime it says it can't find eslint.

I didn't identified any root cause for now. It happens on different files, on different projects, regarding different errors...

**Comment by Mrsevic** [comment]
I am currently experimenting with this extension. Seems much sleeker:
https://github.com/glat/MultiLinter

**Comment by woldner** [comment]
Sorry everyone; but the development of this extension has been suspended. 
You can read more about it here:
https://github.com/jwldnr/VisualLinter#deprecated

**Comment by Indigo744** [comment]
I'm sorry @jwldnr, but I'll use this thread to report about https://github.com/glat/MultiLinter and our discussion with @glat

@Mrsevic  since you tried the extension, you should read this.

Alright so I went to https://github.com/glat/MultiLinter and asked about where is the source code, since I prefer to have a look at what I'm about to install on my machine (and all our team machine). The conversation was... surprising to say the least, and the issue was deleted altogether.

Here is a snapshot of the issue before it was removed:
![image](https://user-images.githubusercontent.com/7137528/68990883-d6ac9400-0858-11ea-9e29-cf6eb0bd6e2d.png)
![image](https://user-images.githubusercontent.com/7137528/68990886-dd3b0b80-0858-11ea-9a83-58ffb628f3eb.png)

I don't know what is the matter with this @glat dude, but he seems... off.

So I wouldn't trust him a bit. Who knows what he is doing with this extension? I'll try to report it to Microsoft to see if they can take a look.

@jwldnr I would say not to recommend this extension. I would even go to actively NOT recommending this extension, based on this.

**Comment by glat** [comment]
Do what you want. Feel free to contact Microsoft. Feel free to delete the extension on the marketplace. The source will remain closed. I sent a pull request on this old extension and the author filled me with comments on what I should wrote and on what extension I should use to improve my source code (Resharper). I hate resharper and I hate non-constructive criticism.

I made your work and deleted any reference to the extension on the web.

It should be MY choice to publish the source code. Yours is to install my extension or not. Again I note that you do not respect my choices, but I MUST respect yours. This is not the kind of work I love to do. I completely rewrote a new extension according my needs and what I think it should be because other programmers does not like my ideas. Sources will never be published because IT'S MY CHOICE. You can't force me to publish it even if the extension is on the marketplace, but of course my ideas ARE NOT YOURS and this is not good, according to you.

So the result is that if you do not trust my extension no other one MUST.

I'll use it for my needs.

To other users of MultiLinter. The extension was deleted because these guys tried to FORCE ME to publish source code, against my will.

**Comment by woldner** [comment]
I honestly have no idea how I got dragged into this.

The development of VisualLinter has been discontinued. And since this project is licensed under MIT anyone has the right to use this code in their own project.

**Comment by glat** [comment]
I contacted @Mrsevic by email.

If he agrees to not publish it I will send him the source code to check for any malware you ARE DESPERATELY SEARCHING so he can give a third party opinion.

To @Mrsevic if you want to help me feel free to contact me by repling my email.

Again, MultiLinter is a complete REWRITE and again, IT'S MY CHOICE TO NOT PUBLISH THE SOURCE CODE. YOU ARE FORCING ME TO DO IT and the one is not understanding WHY is me.

I asked in that issue (WHICH WAS NOT AN ISSUE) to end the discussion two times, and you do not stopped bugging me.
You asked WHY? The answer is that I DO NOT WANT and that should be sufficient for any needs.

Furthermore I DO NOT UNDERSTAND why review my extension with lowest possible ranking and wrote a comment like this:

![image](https://user-images.githubusercontent.com/569200/68991671-6ce4b800-0861-11ea-9b41-82a203c615d4.png)

Do you comment as that for any closed source project you're using? A question: do you use Windows? Do you use Visual Studio? According to my knowledge they are both closed source, but you trust them.
WHY you place this comments ONLY BECAUSE MY EXTENSION IS CLOSED SOURCE?

**Comment by Mrsevic** [comment]
First of all, to the both authors thank you for your hard work, I am sure that it is appreciated by many users who like me downloaded the extension but choose not to leave the rating before properly testing it.

If there is one trend that has been happening recently that I hate in it's very root, it is the mob justice which thankfully didn't happened here. I sincerely hope that @Indigo744 never had such intentions towards the author. 

I am so sad that @glat is retiring his extensions because not every user uses Visual studio Code or .NET Rider, in fact I wrote an relatively lengthy issue and when I tried publishing I have noticed that the repo disappeared.

I think that @Indigo744 should put the ball down, there was absolutely no reason for this backslash. The original authors work was published under MIT license, even if he did a fork of this project(which he did not if you take a look at the sheer size of the extension) he should have just included the original's author's name in the project. Second thing if you want to the decompile the source from the extensions there are methods. If you wanted to see whether or not extension is doing something malicious(it got published and I am pretty sure Microsoft does not let any extension to be published) you could look at the requests. Otherwise any serious AV engine would have reported something. 

@glat Thank you for the explanation and motivations, you should not have been involved in this discussion whatsoever(I do not think that even in this case there was an need for uppercase letters but I could imagine how you felt). I will respond to you as soon as possible as I have certain obligations at this moment. Thank you for contacting me.

**Comment by glat** [comment]
@Mrsevic thanks for your words.

@jwldnr you are not involved in this except because you were the motivation for the birth of MultiLinter.

To any other MultiLinter users I'm evaluting about on continue to support the extension outside of GitHub and the marketplace (where uncorrect reviews comes all days) by creating a web page.

Even today is not the day to think about that.

To any others asking how I was capable to create such extension without a fork, here is all you need to do: https://github.com/microsoft/VSSDK-Extensibility-Samples

**Comment by Indigo744** [comment]
Wow this has gotten out of hand so quickly.

I opened an issue and politely ask a simple, honest question. I was expecting an answer along the line of _"I prefer to keep it close because X and Y, I hope you understand, thank you for your interest"_. You know, a simple answer. Two human being communicating. I would have shrugged and move on. His code, his choices.

Then, I don't know why, @glat started being extremely weird and flippant about it. I mean, why involve @jwldnr? Why say things like "I can't state publicly" and so on...

**I just wanted to understand.** I was always polite.

Then he deleted the whole thread.

I am sorry, but you have to admit, this was (and still is!) suspicious. I mean, trust is important. Even so with third-party extensions. 

So I though that I had to, at least, warn people about it so they _know_ something was amiss. I mean, who sane person would react that way? What _if_ something shady was going on? Would someone like to be warned?

Then he got mad and deleted everything related to his extension.

Wow man. Talk about being even _more_ suspicious!

Please note that I never insulted or threatened or anything. I don't like confrontation. I always thrive to be polite in any circumstance. But when I find something suspicious, I'll report it. It is our duty, as a community of developers relying on trust.

Please note that I never said that this extension was full of malware or anything. Of course this is something I don't know. I just reported what I just experienced while trying to communicate with the author, that is, him being weird about it.

Please note that I never asked for disclosing the source or whatever. Again, his code, his choice. I am not a strong open-source advocate. While I love open source, I know closed-source software are needed. I even work on them daily.

In all these year on Github and other dev communities, I have never seen someone so overly dramatic and reacting so intensely.

In the end, all of this is massively sad. Now Visual Studio doesn't have any proper extension for ESLint support.

**Comment by glat** [comment]
Well, if this is your reply MultiLinter has died.

**Comment by glat** [comment]
So you've no problem about closed-source?

![image](https://user-images.githubusercontent.com/569200/68994319-f4422380-0881-11ea-81a4-20d879e312ef.png)

You started that issue because you was *claiming* to find the source code. Well, I've some news:

1. That is not the kind of issue you've to open. I accept issue about bugs and that was opened and resolved in *hours*
2. You should not expect to find source code in every repository. I was using that repository to store the config file for users usage and to track issues.
3. You are stating, even now, that I'm insane. Well, I'm not. If you do not understand my motivations the problem is your.

I should close this after your last reply, but I can't if you continue to not understand, continue to give me as *insane* and do not understand that I asked *two* times to terminate the discussion and you continued.

Also, it's not first time that I receive a review on VS Marketplace. I know how users like you do. You place a review without even trying the extension. Is this a correct behaviour according to you?

So you're polite? I don't think...

**Comment by Indigo744** [comment]
Who called you insane? When? I said your reaction was _weird_. That your answers were _off_.

> I can't state publicly what I think.

> Perhaps you've no problem, but I've lot of them.

_That_ is why I asked what is the issue about us talking about your source code. You are the one making it sounds like it's a crime. Are you under duress or something?

I continued to try to discuss because you never actually answered. You kept giving evasive reply. Then you deleted the thread. This is clearly not how a discussion works.

In any case, you clearly misread my intention. I merely wanted more information on your extension, which looked really promising as suggested by @Mrsevic 

As a matter of facts, it's not unusual to find a repo with only a readme. A lot of times, it's because the author is using another host, like GitLab or BitBucket (or even sourceforge) and is using GitHub only as a issue repository. Maybe the link was missing from the readme? How should I know?! Why couldn't we discuss it?

I mean, _come on_.

**Comment by glat** [comment]
![image](https://user-images.githubusercontent.com/569200/68994831-88fb5000-0887-11ea-8f68-b88f595cde83.png)

Well I know how to take screenshot as well. You continue on this way... Furthermore:

![image](https://user-images.githubusercontent.com/569200/68995038-a7fae180-0889-11ea-9b75-590dd66c814a.png)

I never answered? Read above. MultiLinter *was* and *will be* forever a closed source. Do you read?

I misread your intention? Your intention was not to try the extension. You'll started to ask where the source code was and even *now* you are here to ask again and stating that my behaviour is suspect. Well, you can state that my behaviour is suspect when you''ll know my motivation, and sure you can't force me to explain that.

We're discussing about it but you're not hearing me. *it's closed source because I want so*
Do you understand?

**Comment by Indigo744** [comment]
Well, you never actually answered in the original thread, before deleting it, which started this whole shenanigans. You didn't even say that it was closed-source. I had to start reporting it here for you to come over and start properly explaining.

 > You'll started to ask where the source code was and even now you are here to ask again.
 > We're discussing about it but you're not hearing me. it's closed source because I want so
Do you understand?

What? No, I am not asking for your code! I even said _"your code, your choice"_ (well it was more _"his code, his choice"_ but I was obviously talking about you). How can you still misinterpret that?

**Alright, let me make this crystal clear for you**: I don't care about your code. I cared a little bit originally, out of interests when looking for a good extension, but now I couldn't care less. I wouldn't touch this thing with a 10-foot pole.

**And yes!** You seem off. This whole discussion is off! This whole turn of events is off! If I knew this morning that I would get into that kind of stuff, I would have stayed in bed and enjoy a blissful peace. But noooo. So much time wasted just because you couldn't even reply normally to a simple, innocent question.

I shouldn't even _bother_ replying anymore. Keep thinking whatever you want.

Take care.

@jwldnr I'll let you decide if you want to lock this thread. I'm awfully sorry for all of this nonsense.

**Comment by glat** [comment]
Well, to be clear:

1. Two posts above I was non answering, now I answered here.
2. Even now you are stating that I forked VisualLinter.
3. I'm really happy you didn't touch my code. I never will be.
4. So you finally stated that I'm off or insane. Great.
5. I've no obligation to answer what you want when you want. I asked to close the issue *two* times because I did not want to discuss about it. Who continued about this? Who wrote that review on Marketplace? Who used this issue to spread the word that I'm insane?
6. I'm still waiting for a single word that you will never write. That is relevant.
